version: '3.1'

services:
  pos:
    container_name: db
    restart: always
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
#    volumes:
#      - ./pg_data:/var/lib/postgresql/data
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
#      interval: 30s
#      timeout: 30s
#      retries: 3

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "5050:5050"